"""Generated by python -m generator from modern xcresulttool schemas.

Do not edit manually. Enum strings are decoded forward-compatibly.
Summary.devicesAndConfigurations and Activities.testRuns use verified wire arrays;
see generator.correct_schema_errors for the Apple schema corrections and evidence.
"""

from __future__ import annotations

# Apple JSON property names are intentionally preserved.
# pylint: disable=invalid-name


from dataclasses import dataclass
from typing import Literal, TypeAlias


from xcresult.model_base import XcresultObject

SCHEMA_VERSION = "0.4.0"


@dataclass(kw_only=True)
class Summary(XcresultObject):
    """Modern xcresulttool Summary data."""

    title: str
    startTime: float | None = None
    finishTime: float | None = None
    environmentDescription: str
    topInsights: list[InsightSummary]
    result: TestResult
    totalTestCount: int
    passedTests: int
    failedTests: int
    skippedTests: int
    expectedFailures: int
    statistics: list[Statistic]
    devicesAndConfigurations: list[DeviceAndConfigurationSummary]
    testFailures: list[TestFailure]
    runtimeWarnings: list[Issue]


@dataclass(kw_only=True)
class InsightSummary(XcresultObject):
    """Modern xcresulttool InsightSummary data."""

    impact: str
    category: str
    text: str


@dataclass(kw_only=True)
class Statistic(XcresultObject):
    """Modern xcresulttool Statistic data."""

    title: str
    subtitle: str


@dataclass(kw_only=True)
class DeviceAndConfigurationSummary(XcresultObject):
    """Modern xcresulttool DeviceAndConfigurationSummary data."""

    device: Device
    testPlanConfiguration: Configuration
    passedTests: int
    failedTests: int
    skippedTests: int
    expectedFailures: int


@dataclass(kw_only=True)
class Device(XcresultObject):
    """Modern xcresulttool Device data."""

    deviceId: str
    deviceName: str
    architecture: str
    modelName: str
    platform: str | None = None
    osVersion: str
    osBuildNumber: str | None = None


@dataclass(kw_only=True)
class Configuration(XcresultObject):
    """Modern xcresulttool Configuration data."""

    configurationId: str
    configurationName: str


@dataclass(kw_only=True)
class TestFailure(XcresultObject):
    """Modern xcresulttool TestFailure data."""

    testName: str
    targetName: str
    failureText: str
    testIdentifier: int
    testIdentifierString: str
    testIdentifierURL: str | None = None


@dataclass(kw_only=True)
class Issue(XcresultObject):
    """Modern xcresulttool Issue data."""

    issueType: str
    message: str
    targetName: str | None = None
    sourceURL: str | None = None
    className: str | None = None


@dataclass(kw_only=True)
class Tests(XcresultObject):
    """Modern xcresulttool Tests data."""

    testPlanConfigurations: list[Configuration]
    devices: list[Device]
    testNodes: list[TestNode]


@dataclass(kw_only=True)
class TestNode(XcresultObject):
    """Modern xcresulttool TestNode data."""

    nodeIdentifier: str | None = None
    nodeIdentifierURL: str | None = None
    nodeType: TestNodeType
    name: str
    details: str | None = None
    duration: str | None = None
    durationInSeconds: float | None = None
    result: TestResult | None = None
    tags: list[str] | None = None
    sourceLocation: SourceLocation | None = None
    children: list[TestNode] | None = None


@dataclass(kw_only=True)
class SourceLocation(XcresultObject):
    """Modern xcresulttool SourceLocation data."""

    filePath: str
    lineNumber: int


@dataclass(kw_only=True)
class TestDetails(XcresultObject):
    """Modern xcresulttool TestDetails data."""

    testIdentifier: str
    testIdentifierURL: str | None = None
    testName: str
    testDescription: str
    duration: str
    durationInSeconds: float | None = None
    startTime: float | None = None
    testPlanConfigurations: list[Configuration]
    devices: list[Device]
    arguments: list[TestDetailsArgumentsItem] | None = None
    testRuns: list[TestNode]
    testResult: TestResult
    hasPerformanceMetrics: bool
    hasMediaAttachments: bool
    tags: list[str] | None = None
    bugs: list[Bug] | None = None
    functionName: str | None = None


@dataclass(kw_only=True)
class Bug(XcresultObject):
    """Modern xcresulttool Bug data."""

    url: str | None = None
    identifier: str | None = None
    title: str | None = None


@dataclass(kw_only=True)
class Activities(XcresultObject):
    """Modern xcresulttool Activities data."""

    testIdentifier: str
    testIdentifierURL: str | None = None
    testName: str
    testRuns: list[TestRunActivities]


@dataclass(kw_only=True)
class TestRunActivities(XcresultObject):
    """Modern xcresulttool TestRunActivities data."""

    device: Device
    testPlanConfiguration: Configuration
    arguments: list[TestRunActivitiesArgumentsItem] | None = None
    activities: list[ActivityNode]


@dataclass(kw_only=True)
class ActivityNode(XcresultObject):
    """Modern xcresulttool ActivityNode data."""

    title: str
    startTime: float | None = None
    attachments: list[ActivityAttachment] | None = None
    isAssociatedWithFailure: bool
    activityType: str | None = None
    childActivities: list[ActivityNode] | None = None


@dataclass(kw_only=True)
class ActivityAttachment(XcresultObject):
    """Modern xcresulttool ActivityAttachment data."""

    name: str
    payloadId: str | None = None
    uuid: str
    timestamp: float | None = None
    lifetime: str


@dataclass(kw_only=True)
class BuildResults(XcresultObject):
    """Modern xcresulttool BuildResults data."""

    actionTitle: str | None = None
    destination: Device
    startTime: float
    endTime: float
    status: str | None = None
    analyzerWarningCount: int | None = None
    errorCount: int | None = None
    warningCount: int | None = None
    analyzerWarnings: list[Issue]
    warnings: list[Issue]
    errors: list[Issue]


@dataclass(kw_only=True)
class ContentAvailability(XcresultObject):
    """Modern xcresulttool ContentAvailability data."""

    hasCoverage: bool
    hasDiagnostics: bool
    hasTestResults: bool
    logs: list[str]


@dataclass(kw_only=True)
class TestAttachmentDetails(XcresultObject):
    """Modern xcresulttool TestAttachmentDetails data."""

    testIdentifier: str
    testIdentifierURL: str | None = None
    attachments: list[Attachment]


@dataclass(kw_only=True)
class Attachment(XcresultObject):
    """Modern xcresulttool Attachment data."""

    exportedFileName: str
    suggestedHumanReadableName: str
    isAssociatedWithFailure: bool
    timestamp: float | None = None
    configurationName: str
    deviceName: str
    deviceId: str
    repetitionNumber: int | None = None
    arguments: list[str] | None = None


@dataclass(kw_only=True)
class TestDetailsArgumentsItem(XcresultObject):
    """Modern xcresulttool TestDetailsArgumentsItem data."""

    value: str


@dataclass(kw_only=True)
class TestRunActivitiesArgumentsItem(XcresultObject):
    """Modern xcresulttool TestRunActivitiesArgumentsItem data."""

    value: str


TestResult: TypeAlias = Literal["Passed", "Failed", "Skipped", "Expected Failure", "unknown"] | str


TestNodeType: TypeAlias = (
    Literal[
        "Test Plan",
        "Unit test bundle",
        "UI test bundle",
        "Test Suite",
        "Test Case",
        "Device",
        "Test Plan Configuration",
        "Arguments",
        "Repetition",
        "Test Case Run",
        "Failure Message",
        "Source Code Reference",
        "Attachment",
        "Expression",
        "Test Value",
        "Runtime Warning",
        "Skip Message",
        "Expected Failure",
    ]
    | str
)


AttachmentDetails: TypeAlias = list[TestAttachmentDetails]


__all__ = [
    "SCHEMA_VERSION",
    "Summary",
    "InsightSummary",
    "TestResult",
    "Statistic",
    "DeviceAndConfigurationSummary",
    "Device",
    "Configuration",
    "TestFailure",
    "Issue",
    "Tests",
    "TestNode",
    "TestNodeType",
    "SourceLocation",
    "TestDetails",
    "Bug",
    "Activities",
    "TestRunActivities",
    "ActivityNode",
    "ActivityAttachment",
    "BuildResults",
    "ContentAvailability",
    "AttachmentDetails",
    "TestAttachmentDetails",
    "Attachment",
    "TestDetailsArgumentsItem",
    "TestRunActivitiesArgumentsItem",
]
